{
 "title": "Example",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total user count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mongodb1_total_user_count" }
   ]
  },
  {
   "title": "Active Template Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "postgres1_template_count" }
   ]
  },
  {
   "title": "successful queries to metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "query2metric_success_count" }
   ]
  },
  {
   "title": "Errors in query to metric",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "query2metric_error_count" }
   ]
  }
 ]
}